config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  resources :clips, only: :update
  post "/reward_claims/:id", to: "reward_claims#create", as: :reward_claims
  root "bars#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar < ApplicationRecord

  def self.default_points
    where(default:true).first.points
  end
end

app/models/child.rb
class Child < ApplicationRecord
  has_many :scores
  has_many :reward_claims
  has_one :clip

  after_create :create_clip

  def total_rewards
    scores.sum(:points) / Bar.maximum(:points)
  end

  def score_and_reset
    scores.create(points: clip.points)
    clip.reset
  end

  def claim(reward)
    if total_rewards < reward.cost
      false
    else
      self.reward_claims.create(name: reward.name, cost: reward.cost)
    end
  end

  def self.score_and_reset
    self.all.each do |child|
      child.score_and_reset
    end
  end


  private

  def create_clip
    clip = self.build_clip(points: Bar.default_points)
    clip.save
  end
end

app/models/clip.rb
class Clip < ApplicationRecord
  belongs_to :child

  def reset
    self.points = Bar.default_points
    self.save
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
end

app/models/reward_claim.rb
class RewardClaim < ApplicationRecord
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :child

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_child

  def current_child
    Child.first
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController

  def index
    @clip = current_child.clip
    @bars = Bar.order(points: :desc)
    @rewards = Reward.order(cost: :desc)
  end
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController

  def update
    @clip = current_child.clip
    @clip.points = params[:points]
    @clip.save
    redirect_to root_url
  end
end

app/controllers/reward_claims_controller.rb
class RewardClaimsController < ApplicationController

  def create
    reward = Reward.find(params[:id])
    if current_child.claim(reward)
      redirect_to root_url, notice: "woohoo!"
    else
      redirect_to root_url, error: current_child.errors.full_messages
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bar_helper.rb
module BarHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/views/bars/_bar.html.erb
<div class="row">
  <div class="col s12">
    <%= button_to @clip, method: :patch, params: { points: bar.points }, class:"waves-effect waves-light btn #{bar.color} bar" do %>
      <%= bar.name %>
      <% if bar.points == @clip.points %>
        <i class="large material-icons right">stars</i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bars/_rewards_modal.html.erb
<div id="modal" class="modal">
  <div class="modal-content">
    <h4>Claim Rewards</h4>
    <%= render @rewards %>
  </div>
</div>

app/views/bars/index.html.erb
<div class="container">
  <%= render @bars %>

  <div class="row">
    <div class="col s3 right">
      <a class="waves-effect waves-light btn pink" href="#modal">
        Claim Rewards: <%= current_child.total_rewards %>
      </a>
    </div>
  </div>
  <%= render 'rewards_modal' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Behavior</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "http://fonts.googleapis.com/icon?family=Material+Icons" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js" %>

  </head>

  <body>
    <%= render 'layouts/shared/notices' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_notices.html.erb
<% display = flash[:error].present? ? '' : 'display:none' %>
<div class="row" style="<%= display %>">
  <div class="col s12">
    <div class="card red lighten-1">
      <div class="card-content red-lighten-1">
        <span class="card-title white-text">Uh-Oh!</span>
      </div>
    </div>
  </div>
</div>

<% display = flash[:notice].present? ? '' : 'display:none' %>
<div class="row" style="<%= display %>">
  <div class="col s12">
    <div class="card green lighten-1">
      <div class="card-content red-lighten-1">
        <span class="card-title white-text">Success!</span>
      </div>
    </div>
  </div>
</div>

app/views/rewards/_reward.html.erb
<div class="row">
  <div class="col s12">
    <%= button_to reward_claims_path(reward.id), class:"waves-effect waves-light btn bar" do %>
      <%= reward.name %> (<%= reward.cost %>)
    <% end %>
  </div>
</div>